[package]
name = "mindmap"
version = "0.1.0"
authors = ["Julianne Natalie Stingray <flat.bartender@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
